language: python

addons:
  postgresql: "9.3"

matrix:
  include:
  - python: 2.7
    env: DJANGO_VERSION=1.11.12 DB=postgres
  - python: 2.7
    env: DJANGO_VERSION=1.11.12 DB=sqlite
  - python: 2.7
    env: DJANGO_VERSION=1.11.12 DB=mysql

  - python: 2.7
    env: DJANGO_VERSION=1.7.11 DB=postgres
  - python: 2.7
    env: DJANGO_VERSION=1.7.11 DB=sqlite
  - python: 2.7
    env: DJANGO_VERSION=1.7.11 DB=mysql

  - python: 2.7
    env: DJANGO_VERSION=1.6.11 DB=postgres
  - python: 2.7
    env: DJANGO_VERSION=1.6.11 DB=sqlite
  - python: 2.7
    env: DJANGO_VERSION=1.6.11 DB=mysql

  - python: 3.6
    env: DJANGO_VERSION=2.0.4 DB=postgres
  - python: 3.6
    env: DJANGO_VERSION=2.0.4 DB=mysql
  - python: 3.6
    env: DJANGO_VERSION=2.0.4 DB=sqlite

  - python: 3.6
    env: DJANGO_VERSION=1.11.12 DB=postgres
  - python: 3.6
    env: DJANGO_VERSION=1.11.12 DB=sqlite
  - python: 3.6
    env: DJANGO_VERSION=1.11.12 DB=mysql

# command to install dependencies
install:
  - "pip install -q Django==$DJANGO_VERSION"
  - "if [[ $DB == mysql ]]; then pip install mysql-python; fi"
  - "if [[ $DB == postgres ]]; then pip install -q psycopg2; fi"

before_script:
  - psql -c 'create database django_positions;' -U postgres
  - mysql -e 'create database django_positions;'

# command to run tests
script: python manage.py test --settings examples.ci_settings_$DB examples
